"""add eksim table

Revision ID: 03cb2a0e2a9f
Revises: 0e3ae103347d
Create Date: 2026-04-12 15:10:40.392078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cb2a0e2a9f'
down_revision: Union[str, Sequence[str], None] = '0e3ae103347d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eksim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('satuan', sa.String(), nullable=False),
    sa.Column('konversi', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', 'tahun', 'freq', 'period', name='uq_eksim_kode_time')
    )
    op.create_index('idx_eksim_lookup', 'eksim', ['kode', 'freq', 'tahun', 'period'], unique=False)
    op.create_index(op.f('ix_eksim_freq'), 'eksim', ['freq'], unique=False)
    op.create_index(op.f('ix_eksim_id'), 'eksim', ['id'], unique=False)
    op.create_index(op.f('ix_eksim_kode'), 'eksim', ['kode'], unique=False)
    op.create_index(op.f('ix_eksim_period'), 'eksim', ['period'], unique=False)
    op.create_index(op.f('ix_eksim_tahun'), 'eksim', ['tahun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eksim_tahun'), table_name='eksim')
    op.drop_index(op.f('ix_eksim_period'), table_name='eksim')
    op.drop_index(op.f('ix_eksim_kode'), table_name='eksim')
    op.drop_index(op.f('ix_eksim_id'), table_name='eksim')
    op.drop_index(op.f('ix_eksim_freq'), table_name='eksim')
    op.drop_index('idx_eksim_lookup', table_name='eksim')
    op.drop_table('eksim')
    # ### end Alembic commands ###
