"""add satuan and konversi column in pkrt table

Revision ID: 0e3ae103347d
Revises: 4be4edbb3037
Create Date: 2026-04-09 20:51:04.055238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3ae103347d'
down_revision: Union[str, Sequence[str], None] = '4be4edbb3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkrt', sa.Column('satuan', sa.String(), nullable=False))
    op.add_column('pkrt', sa.Column('konversi', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pkrt', 'konversi')
    op.drop_column('pkrt', 'satuan')
    # ### end Alembic commands ###
