"""add pdb table

Revision ID: 4be4edbb3037
Revises: b1bbad857c04
Create Date: 2026-04-08 07:55:43.678442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be4edbb3037'
down_revision: Union[str, Sequence[str], None] = 'b1bbad857c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('jenis', sa.String(length=4), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', 'jenis', 'tahun', 'freq', 'period', name='uq_pdb_kode_time')
    )
    op.create_index('idx_pdb_lookup', 'pdb', ['kode', 'jenis', 'freq', 'tahun', 'period'], unique=False)
    op.create_index(op.f('ix_pdb_freq'), 'pdb', ['freq'], unique=False)
    op.create_index(op.f('ix_pdb_id'), 'pdb', ['id'], unique=False)
    op.create_index(op.f('ix_pdb_jenis'), 'pdb', ['jenis'], unique=False)
    op.create_index(op.f('ix_pdb_kode'), 'pdb', ['kode'], unique=False)
    op.create_index(op.f('ix_pdb_period'), 'pdb', ['period'], unique=False)
    op.create_index(op.f('ix_pdb_tahun'), 'pdb', ['tahun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdb_tahun'), table_name='pdb')
    op.drop_index(op.f('ix_pdb_period'), table_name='pdb')
    op.drop_index(op.f('ix_pdb_kode'), table_name='pdb')
    op.drop_index(op.f('ix_pdb_jenis'), table_name='pdb')
    op.drop_index(op.f('ix_pdb_id'), table_name='pdb')
    op.drop_index(op.f('ix_pdb_freq'), table_name='pdb')
    op.drop_index('idx_pdb_lookup', table_name='pdb')
    op.drop_table('pdb')
    # ### end Alembic commands ###
