"""add index jenis_file and UniqueConstraint

Revision ID: 759380c35c6d
Revises: e639fb46262f
Create Date: 2026-05-03 07:40:43.799568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759380c35c6d'
down_revision: Union[str, Sequence[str], None] = 'e639fb46262f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_jenis_file'), 'files', ['jenis_file'], unique=False)
    op.create_unique_constraint('uq_filename_jenis', 'files', ['filename', 'jenis_file'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_filename_jenis', 'files', type_='unique')
    op.drop_index(op.f('ix_files_jenis_file'), table_name='files')
    # ### end Alembic commands ###
