"""initial schema

Revision ID: c1a87207399f
Revises: 
Create Date: 2026-03-12 13:35:32.418640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a87207399f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkrt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', 'tahun', 'freq', 'period', name='uq_pkrt_kode_time')
    )
    op.create_index('idx_pkrt_lookup', 'pkrt', ['kode', 'freq', 'tahun', 'period'], unique=False)
    op.create_index(op.f('ix_pkrt_freq'), 'pkrt', ['freq'], unique=False)
    op.create_index(op.f('ix_pkrt_id'), 'pkrt', ['id'], unique=False)
    op.create_index(op.f('ix_pkrt_kode'), 'pkrt', ['kode'], unique=False)
    op.create_index(op.f('ix_pkrt_period'), 'pkrt', ['period'], unique=False)
    op.create_index(op.f('ix_pkrt_tahun'), 'pkrt', ['tahun'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_pkrt_tahun'), table_name='pkrt')
    op.drop_index(op.f('ix_pkrt_period'), table_name='pkrt')
    op.drop_index(op.f('ix_pkrt_kode'), table_name='pkrt')
    op.drop_index(op.f('ix_pkrt_id'), table_name='pkrt')
    op.drop_index(op.f('ix_pkrt_freq'), table_name='pkrt')
    op.drop_index('idx_pkrt_lookup', table_name='pkrt')
    op.drop_table('pkrt')
    # ### end Alembic commands ###
