"""add pkp table

Revision ID: e55480da741c
Revises: fc15b30ac439
Create Date: 2026-04-12 20:32:47.810385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55480da741c'
down_revision: Union[str, Sequence[str], None] = 'fc15b30ac439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('satuan', sa.String(), nullable=False),
    sa.Column('konversi', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', 'tahun', 'freq', 'period', name='uq_pkp_kode_time')
    )
    op.create_index('idx_pkp_lookup', 'pkp', ['kode', 'freq', 'tahun', 'period'], unique=False)
    op.create_index(op.f('ix_pkp_freq'), 'pkp', ['freq'], unique=False)
    op.create_index(op.f('ix_pkp_id'), 'pkp', ['id'], unique=False)
    op.create_index(op.f('ix_pkp_kode'), 'pkp', ['kode'], unique=False)
    op.create_index(op.f('ix_pkp_period'), 'pkp', ['period'], unique=False)
    op.create_index(op.f('ix_pkp_tahun'), 'pkp', ['tahun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pkp_tahun'), table_name='pkp')
    op.drop_index(op.f('ix_pkp_period'), table_name='pkp')
    op.drop_index(op.f('ix_pkp_kode'), table_name='pkp')
    op.drop_index(op.f('ix_pkp_id'), table_name='pkp')
    op.drop_index(op.f('ix_pkp_freq'), table_name='pkp')
    op.drop_index('idx_pkp_lookup', table_name='pkp')
    op.drop_table('pkp')
    # ### end Alembic commands ###
