"""add monitoring table

Revision ID: e639fb46262f
Revises: fe2a3fb27c85
Create Date: 2026-04-21 14:12:48.815016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e639fb46262f'
down_revision: Union[str, Sequence[str], None] = 'fe2a3fb27c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('komponen', sa.String(length=100), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('nama_data', sa.Text(), nullable=False),
    sa.Column('internal_external', sa.String(length=30), nullable=True),
    sa.Column('pjk_neraca', sa.String(length=30), nullable=True),
    sa.Column('penanggung_jawab', sa.Text(), nullable=True),
    sa.Column('jumlah_data', sa.Integer(), nullable=False),
    sa.Column('jumlah_datum', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=True),
    sa.Column('nilai', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('freq', sa.String(length=20), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('komponen', 'no', 'tahun', 'bulan', name='uq_monitoring_periode')
    )
    op.create_index('idx_monitoring_dataset', 'monitoring', ['komponen', 'no'], unique=False)
    op.create_index('idx_monitoring_freq', 'monitoring', ['freq'], unique=False)
    op.create_index('idx_monitoring_tahun_bulan', 'monitoring', ['tahun', 'bulan'], unique=False)
    op.create_index('idx_monitoring_tahun_freq', 'monitoring', ['tahun', 'freq'], unique=False)
    op.create_index(op.f('ix_monitoring_id'), 'monitoring', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_id'), table_name='monitoring')
    op.drop_index('idx_monitoring_tahun_freq', table_name='monitoring')
    op.drop_index('idx_monitoring_tahun_bulan', table_name='monitoring')
    op.drop_index('idx_monitoring_freq', table_name='monitoring')
    op.drop_index('idx_monitoring_dataset', table_name='monitoring')
    op.drop_table('monitoring')
    # ### end Alembic commands ###
