"""add pmtb table

Revision ID: fc15b30ac439
Revises: 03cb2a0e2a9f
Create Date: 2026-04-12 19:03:06.220624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc15b30ac439'
down_revision: Union[str, Sequence[str], None] = '03cb2a0e2a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pmtb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('satuan', sa.String(), nullable=False),
    sa.Column('konversi', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode', 'tahun', 'freq', 'period', name='uq_pmtb_kode_time')
    )
    op.create_index('idx_pmtb_lookup', 'pmtb', ['kode', 'freq', 'tahun', 'period'], unique=False)
    op.create_index(op.f('ix_pmtb_freq'), 'pmtb', ['freq'], unique=False)
    op.create_index(op.f('ix_pmtb_id'), 'pmtb', ['id'], unique=False)
    op.create_index(op.f('ix_pmtb_kode'), 'pmtb', ['kode'], unique=False)
    op.create_index(op.f('ix_pmtb_period'), 'pmtb', ['period'], unique=False)
    op.create_index(op.f('ix_pmtb_tahun'), 'pmtb', ['tahun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pmtb_tahun'), table_name='pmtb')
    op.drop_index(op.f('ix_pmtb_period'), table_name='pmtb')
    op.drop_index(op.f('ix_pmtb_kode'), table_name='pmtb')
    op.drop_index(op.f('ix_pmtb_id'), table_name='pmtb')
    op.drop_index(op.f('ix_pmtb_freq'), table_name='pmtb')
    op.drop_index('idx_pmtb_lookup', table_name='pmtb')
    op.drop_table('pmtb')
    # ### end Alembic commands ###
