"""add satuan column in pdb

Revision ID: fe2a3fb27c85
Revises: e55480da741c
Create Date: 2026-04-17 17:38:17.261937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2a3fb27c85'
down_revision: Union[str, Sequence[str], None] = 'e55480da741c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdb', sa.Column('satuan', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdb', 'satuan')
    # ### end Alembic commands ###
